---
title: "model for bankruptcy"
author: "Duong"
date: "3/31/2020"
output: html_document
---

```{r setup, include=FALSE}
library(readxl)
setwd("D:/Thuy Duong/R/VBM-lecture/bankruptcy paper/da ta")
#load("C:/Users/NHATDUY/Dropbox/failure bank/bai viet/bankrupt/data/data_cleaned.RData")
data<-read.csv("data1.csv")
```



#
```{r}
data$Status <-as.factor(data$Status)
data$X <- NULL
data$YearReport<-NULL
```
#Library, chia data
```{r}
library(ggplot2)
library(ModelGood)
library(VIF)
library(InformationValue)
library(lmtest)
library(survey)
library(data.table)
library(e1071)




library(caret)
library(DMwR)

# Training and testing
set.seed(1234)
ind <- sample(2, nrow(data), replace = TRUE, prob = c(0.7, 0.3))
train.d <- data [ind == 1, ]
test.d <- data [ind == 2, ]
# Check bankrupt and nonbankrupt ratio
#prop.table(table(train.d$status))
#prop.table(table(test.d$sta))
table(train.d$Status)
table(test.d$Status)


```




# decision tree theo full bien
```{r echo=TRUE}
#Biến đổi dữ liệu


library ("party")

myFormula <- Status~.

banksd_ctree <- ctree(myFormula, data = train.d)

#print(banksd_ctree) 
nodes(banksd_ctree, 2) 


#plot the tree
#plot(banksd_ctree)




#Đánh giá mô hình trên tập training
table(predict(banksd_ctree), train.d$Status) # bang ket qua du bao
#prop.table(table(predict(banksd_ctree), train.d$status)) # tinh xs du bao 


#Đánh giá mô hình trên tập test
testPred <- predict(banksd_ctree, newdata = test.d)

table(testPred, test.d$Status) # so sanh gia tri thuc te va gia tri du bao
accuracy=mean(testPred==test.d$Status)
print(accuracy)




```
```{r}
str(data)
```


#decision tree voi bien theo lasso
```{r echo=TRUE}


library ("party")

myFormula <- Status~CASHMTA +CHLCT + X.EBIT...DP..AT + INVCHINVT + LCTAT + LTAT + LOG.AT. + MB   + OIADPAT + PRICE +QALCT + SALEAT +SIGMA+ WCAPAT

banksd_ctree <- ctree(myFormula, data = train.d)

print(banksd_ctree) 
nodes(banksd_ctree, 2) 


#plot the tree
#plot(banksd_ctree)




#Đánh giá mô hình trên tập training
table(predict(banksd_ctree), train.d$Status) # bang ket qua du bao
prop.table(table(predict(banksd_ctree), train.d$Status)) # tinh xs du bao 


#Đánh giá mô hình trên tập test
testPred <- predict(banksd_ctree, newdata = test.d)
#testPred <- predict(bds_ctree, newdata = test.data, type ="prob")# du bao theo xs
table(testPred, test.d$Status) # so sanh gia tri thuc te va gia tri du bao
accuracy=mean(testPred==test.d$Status)
print(accuracy)



```




