---
title: "model for bankruptcy"
author: "Duong"
date: "3/31/2020"
output: html_document
---

```{r setup, include=FALSE, echo=TRUE}
# Read Data that are cleaned 
load("data/data_cleaned.RData")
```

#Library, chia data
```{r echo=TRUE}
library(ggplot2)
library(ModelGood)
library(VIF)
library(InformationValue)
library(lmtest)
library(survey)
library(data.table)
library(e1071)

library(abind)
# split data
library(caret)
library(DMwR)
library(ROSE)

#Training and testing
set.seed(1234)
# sample theo row
# ind <- sample(2, nrow(data), replace = TRUE, prob = c(0.7, 0.3))
# train.d <- data [ind == 1, ]
# test.d <- data [ind == 2, ]
# sample theo company
ind_com <- sample(2,nrow(tick_num)/3,replace = TRUE,prob = c(0.7,0.3))
num_firms <- unique(tick_num[,1])
train_lot <- num_firms[ind_com==1]
test_lot <- num_firms[ind_com==2]
train.d_lot <- tick_num[is.element(tick_num[,1],train_lot),2]
test.d_lot <- tick_num[is.element(tick_num[,1],test_lot),2]

train.d <- data[train.d_lot,]
test.d <- data [test.d_lot,]
# Check bankrupt and nonbankrupt ratio
#prop.table(table(train.d$status))
#prop.table(table(test.d$sta))
table(train.d$Status)
table(test.d$Status)

```



#logistic full variables
```{r echo=TRUE}

#ctrl<-trainControl(method="cv", number=5)
LogitMod <- glm(Status ~ ., data=train.d,
                family=binomial(link="logit"))
                #trControl = ctrl)  # build linear regression model on full data
bw_LogitMod = step(LogitMod) # Backwards selection is the default
print(summary(bw_LogitMod))
```
#logistic after stepwise
```{r echo=TRUE}
LogitMod <- glm(Status ~ X1+X2+X3+X4+X5+ X6+ X7+ X8 +X9+ X10 +X11+ X12 +X13+ X14+ X15+ X16+ X17 +X18+ X19+ X20 +X21+ X22+ X23+ X24+ X25+ X26+ X27+ X28+ X29+ X30+ X31 +X32 +X33+ X34 +X35+ X36+ X37, data=train.d, family=binomial(link="logit"))
print(summary(LogitMod))
# Tại sao ở đây lại là logistic after stepwise>ư

# Wald test and LR test
regTermTest(LogitMod, "ITD")
LogitMod_coef <- glm(status ~ 1, data=train.d, family=binomial(link="logit"))
lrtest(LogitMod, LogitMod_coef)

```
#evaluate logistic full variables
```{r echo=TRUE}
library(caret)
predict <- predict(LogitMod, test.d, type = 'response')

## Create Confusion Matrix
table(test.d$status, predict > 0.5)
library(ROCR)
ROCRpred <- prediction(predict, test.d$status)
ROCRperf <- performance(ROCRpred, 'tpr','fpr')
plot(ROCRperf, colorize = TRUE, text.adj = c(-0.2,1.7))

#misClassError(test.d$status, predict, threshold = optCutOff)
plotROC(test.d$status, predict)
```



#logistic theolasso
```{r echo=TRUE}
# Mo hinh logit
LogitMod <- glm(status ~ X2+X3+X5+ X7 +X9+ X10 +X11+  X15 +X18+X20+ X22+ X23+  X25+  X27+ X29+ X30+ X31 +X32+ X34 + X36+ X37, data=train.d,
                family=binomial(link="logit"))  # build linear regression model on full data
bw_LogitMod = step(LogitMod) # Backwards selection is the default
print(summary(bw_LogitMod))



```


#test logistic voi bien lasso
```{r}
library(caret)
predict <- predict(LogitMod, test.d, type = 'response')

## Create Confusion Matrix
table(test.d$status, predict > 0.5)
library(ROCR)
ROCRpred <- prediction(predict, test.d$status)
ROCRperf <- performance(ROCRpred, 'tpr','fpr')
plot(ROCRperf, colorize = TRUE, text.adj = c(-0.2,1.7))

#misClassError(test.d$status, predict, threshold = optCutOff)
plotROC(test.d$status, predict)
```



